name = "IndexedVectors"
uuid = "ce6fd8af-47ce-44eb-b41a-c8253e356a4d"
authors = ["Du Shiqiao <lucidfrontier.45@gmail.com> and contributors"]
version = "0.2.4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
